site_name: Sequelize | The Node.js ORM for PostgreSQL, MySQL, SQLite, Oracle and MSSQL
site_description: Sequelize is an ORM for Node.js. It supports the dialects PostgreSQL, MySQL, SQLite, Oracle and MSSQL.
repo_url: https://github.com/konnecteam/sequelize/
theme: 
  name: readthedocs
extra_css:
- css/style.css

pages:
- Home: index.md
- Getting Started: getting-started.md
- Model Definition: models-definition.md
- Model Usage: models-usage.md
- Querying: querying.md
- Instances: instances.md
- Relations / Associations: associations.md
- Transactions: transactions.md
- Scopes: scopes.md
- Hooks: hooks.md
- Raw queries: raw-queries.md
- Migrations: migrations.md
- Working with legacy tables: legacy.md
- API: api-link.md
- Who's using sequelize?: whos-using.md
- Imprint: imprint.md